version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: shribalajiattire-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shribalajiattire
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: shribalajiattire-backend
    environment:
      SPRING_PROFILE: dev
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: shribalajiattire
      DB_USER: root
      DB_PASSWORD: password
      JWT_SECRET: your-256-bit-secret-key-change-this-in-production-environment-make-it-long
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY:-sk_test_your_stripe_key}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET:-whsec_your_webhook_secret}
      UPLOAD_DIR: /app/uploads
      UPLOAD_BASE_URL: http://localhost:8080/api/uploads
      CORS_ORIGINS: http://localhost:3000,http://localhost:80
    ports:
      - "8080:8080"
    volumes:
      - backend_uploads:/app/uploads
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:8080/api
    container_name: shribalajiattire-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mysql_data:
  backend_uploads:

networks:
  app-network:
    driver: bridge
