spring:
  application:
    name: shri-balaji-attire
  
  profiles:
    active: ${SPRING_PROFILE:dev}
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev
  
 
  datasource:
    url: jdbc:mysql://localhost:3306/shribalajiattire?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8
    username: sba_user
    password: Sba@StrongPass123
    driver-class-name: com.mysql.cj.jdbc.Driver

  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  sql:
    init:
      mode: always

app:
  jwt:
    secret: ${JWT_SECRET:your-256-bit-secret-key-change-this-in-production-environment}
    expiration: 86400000 # 24 hours
  
  stripe:
    api-key: ${STRIPE_SECRET_KEY:sk_test_your_stripe_key}
    webhook-secret: ${STRIPE_WEBHOOK_SECRET:whsec_your_webhook_secret}
  
  upload:
    dir: ${UPLOAD_DIR:./uploads}
    base-url: ${UPLOAD_BASE_URL:http://localhost:8080/api/uploads}
  
  cors:
    allowed-origins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:5173}

---
# H2 Demo Profile
spring:
  config:
    activate:
      on-profile: h2
  
  datasource:
    url: jdbc:h2:mem:shribalajiattire
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

app:
  jwt:
    secret: ${JWT_SECRET:your-256-bit-secret-key-change-this-in-production-environment}
    expiration: 86400000
  
  stripe:
    api-key: ${STRIPE_SECRET_KEY:sk_test_your_stripe_key}
    webhook-secret: ${STRIPE_WEBHOOK_SECRET:whsec_your_webhook_secret}
  
  upload:
    dir: ${UPLOAD_DIR:./uploads}
    base-url: ${UPLOAD_BASE_URL:http://localhost:8080/api/uploads}
  
  cors:
    allowed-origins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:5173}

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod
  
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000
  
  stripe:
    api-key: ${STRIPE_SECRET_KEY}
    webhook-secret: ${STRIPE_WEBHOOK_SECRET}
  
  upload:
    dir: ${UPLOAD_DIR:/app/uploads}
    base-url: ${UPLOAD_BASE_URL}
  
  cors:
    allowed-origins: ${CORS_ORIGINS}

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# Logging
logging:
  level:
    com.shribalajiattire: ${LOG_LEVEL:INFO}
    org.springframework.security: ${LOG_LEVEL:INFO}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
